### ISSUE TITLE
Review (and fix) symlink handling in type 1 code

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/libappimage#10]
While working on #9, I added a new function, which lacked symlink handling in the type 2 code at first. Therefore, I refactored the code to be more useful, fixed a few annoyances, and implemented some actual error handling (which is missing in the majority of the legacy code of libappimage right now).

Since I didn't encounter issues for type 1 yet, I didn't work on that. However, also that code base should be reviewed, and perhaps refactored soon.

**Comment by azubieta** [comment]
Can you provide uses cases where this bug is present?

**Comment by TheAssassin** [comment]
No. This is more a "review the existing code base and look for (more or less obvious) errors.

**Comment by azubieta** [comment]
This issue has been addressed in 0.1 and 0.2. I think it's safe to close it.
