### ISSUE TITLE
Remove unused source code

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#121]
E.g., is https://github.com/AppImage/libappimage/blob/master/src/libappimage/desktop_integration.c stilll used?

**Comment by azubieta** [comment]
No, it slip in some merge. Can be safely removed.

**Comment by probonopd** [comment]
Please do so, thanks!

**Comment by azubieta** [comment]
addressed at #125

**Comment by TheAssassin** [comment]
Closed by #125.
