### ISSUE TITLE
Notify KDE about changed icons using dbus

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#123]
https://github.com/TheAssassin/AppImageLauncher/blob/9aedcf2cb308c6362bc7eed2b0ba88d388bb2079/src/shared/shared.cpp#L580-L585

When implemented in libappimage, this should not be done using Qt, though. Unless we switch libappimage to Qt.

Reference:
https://github.com/TheAssassin/AppImageLauncher/issues/165

**Comment by azubieta** [comment]
Already investigated this and found that there are no dbus services listening to that signal. Please check the details here https://github.com/AppImage/appimaged/issues/88#issuecomment-497791314

**Comment by azubieta** [comment]
Right now we don't call any desktop update from `libappimage`, first we need to check if we want to do it. Second we should move all the known hacks (not only kde) to `libappimage`

**Comment by probonopd** [comment]
Yes. @TheAssassin wdyt?

**Comment by azubieta** [comment]
Already investigated this issue and the dbus call has no effect so far.
This also seems to be a duplicated of #29 
Will close the issue and the discussions about moving desktop update hacks could continue on #129 
Please feel free to reopen it if required.

**Comment by probonopd** [comment]
>  the dbus call has no effect so far

@TheAssassin why are you using it in AppImageLauncher?

**Comment by TheAssassin** [comment]
I was told this might help in some chat, IIRC. It certainly can't hurt, I'm using Qt anyway, so DBus is easy to use.
