### ISSUE TITLE
Fall back to integrating topmost desktop file

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#127]
Some AppImages currently fail to integrate and are hence missing from the applications menu.

Examples:
* https://github.com/prusa3d/PrusaSlicer/issues/1431
* https://github.com/AppImage/appimage.github.io/pull/1614
* https://github.com/AppImage/appimage.github.io/pull/1615 (at this point I fear that _all_ electron-builder based AppImages are affected)

A `usr/` structure is not strictly required in an AppDir, nor in an AppImage (although it has become  common practice these days). In accordance with the AppImageSpec, we may fall back to integrating topmost desktop file (there should be exactly one in the root directory of an AppImage) in case `usr/share/applications` does not exist in the AppImage.

**Comment by azubieta** [comment]
According to:
https://github.com/AppImage/libappimage/blob/4e251dfeffa8548791a5f2ae9ab49f7148ebd65a/src/libappimage/utils/resources_extractor/ResourcesExtractor.cpp#L37

Using the desktop in the root of the AppDir is the default and only behavior to perform desktop integration. Also tested the [latest PrusaSlicer AppImage](https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.0.0/PrusaSlicer-2.0.0+linux64-201905201652.AppImage) and the desktop entry was created.

**Comment by probonopd** [comment]
That is interesting, did I give the wrong answer in https://github.com/prusa3d/PrusaSlicer/issues/1431 then? Can we even reproduce that issue with `appimaged` and/or `AppImageLauncher`?

**Comment by azubieta** [comment]
I tried it using `appimaged` and the only issue I had was firejail preventing it from running.

**Comment by azubieta** [comment]
I tried it using `appimaged` and the only issue I had was firejail preventing it from running. Maybe that's the same issue they are having

**Comment by azubieta** [comment]
Will close the issue as it's already implemented.
Fell free to reopen it if required.
