### ISSUE TITLE
appimage_type2_get_desktop_filename_and_key_file doesn't load symlinked desktop files

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/libappimage#13]
While looking into https://github.com/TheAssassin/AppImageLauncher/issues/97, I found that if an AppImage uses a symlink for the root desktop file (IIRC linuxdeploy uses that method, too), `appimage_type2_get_desktop_filename_and_key_file` will report success and returns the correct path, however `g_key_file_load_from_squash` doesn't support reading from symlinks, and fails to create the `GKeyFile` instance. For some reason, however, that function doesn't report an error. It makes the assumption that if a file is found in the root directory, it's a regular file. That is not acceptable.

We must:
  - change the function to return an error if loading of the key file fails
  - make that function aware of symlinks

CC @azubieta would appreciate if you could look into that ASAP.

**Comment by azubieta** [comment]
There is a test case in libappimage that covers this, please see https://github.com/AppImage/libappimage/blob/ed440704ed0bb3526ca525a25ceae71950b353d1/tests/test_libappimage.cpp#L525 which makes use of the function in question https://github.com/AppImage/libappimage/blob/103f9559d733ec580c999f84d744c76cd8358eb3/src/libappimage/libappimage.c#L1308

**Comment by TheAssassin** [comment]
Can you test it with the digiKam AppImage by hand, please? That's the one which doesn't work. The two unit tests seem to not cover that issue.
