### ISSUE TITLE
Regarding Desktop Linux Runtime

### ISSUE THREAD

**Issue by varbhat** [AppImage/libappimage#150]
Hello @probonopd  ,

I was reading your [blog post](https://medium.com/@probonopd/so-linux-sucks-can-we-make-a-friendly-libre-desktop-system-e5bdcfe0561a) . You had mentioned the idea of Desktop Linux Runtime .

I am now thinking whether we can create Desktop Linux Runtime ourselves for the Appimage (by using the base of Alpine Linux / similar Distros )?

Also ,these ideas now come into my mind.

1) It must be possible to bake the runtime into the final Appimage/Binary.(to form a single executable)
2) I hope that Appimage type 3 will be statically linked as discussed here (https://github.com/AppImage/AppImageKit/issues/877)
3) Many distros might not include Desktop Runtime. Then,  Appimage must check whether Desktop Runtime is available in package repository. If not, it must download that runtime from the internet(ofc with permission. Those runtime must be hosted somewhere and served)
4) There must be more Runtimes . For ex. , for base-system, graphics , 32-bit support,etc.
5) Now see my 1st point. Ability to bake runtime into final Appimage .During that process, there must be possibility to only extract required things from the runtime , repack them , and bake it into the Appimage .It results in smaller binary.

**Comment by probonopd** [comment]
Hello @varbhat,

then we would essentially end up with `https://snapcraft.io/`.

AppImages are supposed to work on systems without Internet connection, without dependencies on other stuff that needs to be downloaded first.
