### ISSUE TITLE
Update Boost External URL

### ISSUE THREAD

**Issue by WirelessElephant** [AppImage/libappimage#163]
After attempting to build AppImageLauncher, I ran into an issue where the listed server (once appeared to be a sourceforge url, now a bintray url) returned a `502` status code. While this may be temporary, https://boostorg.jfrog.io/artifactory/ is the link returned from the boost.org site for downloading the latest release.

**Comment by TheAssassin** [comment]
https://github.com/AppImage/libappimage/commit/36691c47fc88b5da71d3a24cfd5fdb619905d55a

Should fix the issue.
