### ISSUE TITLE
[desktopintegration] Fails when AppImage has "(" or ")" in name

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#22]
Probably the value after `Exec=` in the generated `.desktop` file needs to be quoted to prevent from this.

**Comment by TheAssassin** [comment]
The shiny, new linuxdeploy desktop file parser will soon receive some code that implements escaping for values of keys where filenames are referenced. Once that's written, it might serve as inspiration for implementing some escaping in libappimage.

**Comment by azubieta** [comment]
Fixed in `libappimage 0.2`. Please reopen if the issue persists.
