### ISSUE TITLE
Thumbnail does not get generated for some AppImages

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#30]
![](https://user-images.githubusercontent.com/2480569/49685247-45755f00-fad8-11e8-9cba-213a46b2f458.png)

`Shotcut-181118.glibc2.14-x86_64.AppImage` from https://github.com/mltframework/shotcut/releases

**Comment by azubieta** [comment]
Tested using `libappimage 0.2`, it works as expected. Please feel free to reopen if the issue persist
