### ISSUE TITLE
Remove redundancy between type2.c and libappimage.c

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#31]
https://github.com/AppImage/libappimage/pull/25#issuecomment-443326105

https://github.com/AppImage/libappimage/blob/8b3969667004659f0033c71556a161bca3d60690/src/libappimage/libappimage.c#L396 and https://github.com/AppImage/libappimage/blob/8b3969667004659f0033c71556a161bca3d60690/src/libappimage/type2.c#L68

**Comment by probonopd** [comment]
Example:

https://github.com/AppImage/libappimage/search?q=SQUASHFS_SYMLINK_TYPE&unscoped_q=SQUASHFS_SYMLINK_TYPE

**Comment by azubieta** [comment]
Being addressed in the new implementation of libappimage.

**Comment by azubieta** [comment]
fixed at ca8d4b53bed5cbc0f3d0398e30806e0d3adeaaab
