### ISSUE TITLE
Replacing elf file reading functions by libelf or LIEF

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#35]
As part of the libappimage rewrite on C++, it's proposed to replace our own ELF files reading functions by a more widely used and tested ones. Those will be [libelf](https://directory.fsf.org/wiki/Libelf) and [LIEF](https://github.com/lief-project/LIEF). The positive aspects of this change are that we will reduce our codebase and the need for maintaining that part. The negative: we will have another dependency.

1. libelf
 - size: ~200 kb
 - license:  LGPL
2. LIEF
 - size: ~ 2Mb
 - license: Apache

Is it viable to have it? Does it imply any licensing issues?

**Comment by TheAssassin** [comment]
CC @probonopd both options might lead to some conflicts with our current MIT licensing. Please review.

**Comment by probonopd** [comment]
Increases licensing complexity, code unknown to us, and adds yet more external dependencies.
Let's not keep adding dependencies for no good reason (and I think "more widely used and tested" is not sufficient reason to justify this).

**Comment by azubieta** [comment]
Just to bring all the evidence before closing this issue.

`libelf` code is much more reliable than our own written code. There are A LOT of applications that rely on it if you have a Debian system at hand please run `apt-rdepends -r libelf1`.

About having another external dependency, this lib is expected to be in almost every GNU/Linux distribution. 

`libappimage` target users will be: urselves and desktop environments looking for a better AppImage support. From the desktop environments point of view there are no issues on symlinking to libelf. From our point of view will imply making the final products that embeds libelf LGPL licensed.

From my point of view there are no issues on making the appimagetool or the appimaged AppImage LGPL. Only the final AppImage will have to be LGPL not the code it self.


The good reason, will be reduce maintenance work. Which allow us to focus on more important things. 
[Standing on the shoulders of giants](https://en.wikipedia.org/wiki/Standing_on_the_shoulders_of_giants) (fuse, libarchive, squashfs, Rox AppDir) has brought the AppImage project this far, why should we stop doing it?

**Comment by azubieta** [comment]
I just found a [BSD licensed](https://opensource.org/licenses/bsd-license.php) implementation of libelf [here](https://sourceforge.net/projects/elftoolchain/). It will allow us to redistribute libappimage keeping the MIT license but only mentioning that the libelf inside it is BSD.

By, the way, it's not my purpose to be annoying. Just want to avoid wheel reinventions where is possible.

**Comment by probonopd** [comment]
Much better! Can we statically link it? (I really don't like this whole dependency thing, for example I never like it when you want to install a third-party deb and the installation fails because it has dependencies on other debs that are not part of the system's default installation, forcing you to `apt-get -f update`.)

**Comment by azubieta** [comment]
Yes, we can statically link it.

About the complexity, I see the fact of using `libelf` as an opportunity of reducing the complexity. We have to deal with less code, there will be fewer memory leaks to hunt and also fewer security flaws. Also we will be delegating all the elf manamement related complexity to `libelf` authors.

**Comment by TheAssassin** [comment]
You're not talking about libelf any more, but some random third-party project.

I am on @probonopd's side, we shouldn't add this dependency.

**Comment by azubieta** [comment]
@TheAssassin please, check the project link again. This is not a random project. It the one used at freeBSD https://wiki.freebsd.org/LibElf

**Comment by probonopd** [comment]
Again, if it ain't broken, don't try to fix it.

**Comment by TheAssassin** [comment]
You can keep the C code for now. I'll volunteer to rewrite it. Ideally, when there are unit tests for that code.
