### ISSUE TITLE
Handle symlinks correctly

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#43]
Please make sure that when the desktop integration functions are called, then e.g., if the desktop file in the top-level directory is a symlink, it is handled correctly.

Reference:
https://github.com/AppImage/appimaged/issues/54

**Comment by TheAssassin** [comment]
Hasn't support been implemented in #25? CC @azubieta

**Comment by azubieta** [comment]
@TheAssassin Indeed, @probonopd would you mind providing the offender AppImage?

**Comment by probonopd** [comment]
AppImageUpdate

**Comment by probonopd** [comment]
Can you have a look at those please @azubieta? Thank you.

**Comment by azubieta** [comment]
Offender AppImages tested on `appimaged` using `libappimave v0.2`. The issue seems solved. Would you mind to validate on your systems?

 `appimaged` using `libappimave v0.2` is available for download from its [releases page](https://github.com/AppImage/appimaged/releases).

**Comment by azubieta** [comment]
Closing, please feel free to reopen if the issue persist
