### ISSUE TITLE
Thumbnail generation at libappimage

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#44]
One of the functionalities that are still missing at libappimage_0.2 is the thumbnails generation. A correct implementation of the standard will require using some image manipulation library (which are known to be huge). The current implementation is really naive as it ignores the Images size and format.

I consider that a correct implementation can easily be achieved by a third party tool without size or linking dependencies restrictions like "appimaged" or "AppImageLaunher". So I would like to leave it out of our public interface.

@probonopd @TheAssassin comments are welcome

This issue is related to #33

**Comment by TheAssassin** [comment]
We already had used `libcairo` or something in the old libappimage. That's one of the reasons why we have this `libappimage_shared` module, it doesn't link to those libraries.

I strongly recommend using CImg for the topic. It's working great in linuxdeploy so far.

**Comment by probonopd** [comment]
I think it might be a good idea to have thumbnail functionality in libappimage indeeed, especially if it does not add extra dependencies.

**Comment by azubieta** [comment]
That's the issue we have to use something in addition. Which means another dependency.

**Comment by azubieta** [comment]
will be solved by #26

**Comment by azubieta** [comment]
fixed at ca8d4b53bed5cbc0f3d0398e30806e0d3adeaaab
