### ISSUE TITLE
Version number in the launcher for type-1 images

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#5]
https://github.com/Ultimaker/cura-build/issues/136#issuecomment-418722012

> have a version number in my launcher

We should rewrite the version appending (and any other such logic) independently from the underlying image format, so that it will work with all current (and future) image formats.

Different image types should not behave differently.

**Comment by TheAssassin** [comment]
@probonopd there is nothing to do here, it's already working for both types... Just add `X-AppImage-Version` to the desktop file...
