### ISSUE TITLE
Implement a proper logging system

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#51]
Currently, libappimage logging is controlled by the "verbose" boolean parameter on some of the public interface functions. This method doesn't allow specifying verbosity levels or pretty printing errors.

**Comment by azubieta** [comment]
Fixed by #85

**Comment by probonopd** [comment]
Please run appimaged without verbose option. You will notice that it outputs a lot of information coming from `libappimage` anyway. This should be changed, so that the output only happens when appimaged is invoked with its verbose option.
