### ISSUE TITLE
cmake LIBAPPIMAGE_LIBRARIES missing

### ISSUE THREAD

**Issue by astippich** [AppImage/libappimage#53]
When I compile libappimage and try to use it in KDE's KFileMetaData (https://phabricator.kde.org/D18450), cmake configuration fails with:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBAPPIMAGE_LIBRARIES
    linked by target "kfilemetadata_appimageextractor" in directory /path_to_folder/kfilemetadata/src/extractors
    linked by target "appimageextractortest" in directory /path_to_folder/kfilemetadata/autotests

Configuring incomplete, errors occurred!
See also "/path_to_folder/build-kfilemetadata-Desktop-Default/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.

This is on Kubuntu 18.10.

I'm not super experienced with this, so this may also be a problem on my side.

**Comment by TheAssassin** [comment]
The variable `LIBAPPIMAGE_LIBRARIES` might have existed once, but I can't recall when/how. Maybe it's still a thing in our exported CMake target config. We rather recommend to link to the `libappimage` target directly.

CC @azubieta if there's still such a variable in the exported targets config, please remove it there to provide a more consistent experience.

**Comment by kossebau** [comment]
`LIBAPPIMAGE_LIBRARIES` is still referred to in the header of the installed `libappimageConfig.cmake` as a variable that is set. Also is there code elsewhere in that file which tries to set the very variable.
But indeed in latest version the result of that varibale is NOTFOUND, so some logic must have regressed in the cmake config file, as this used to work before.
For backward compatibility it would be nice to have `LIBAPPIMAGE_LIBRARIES` still working. Please only drop this when you break ABI elsewhere as well.

**Comment by azubieta** [comment]
should be fixed by #55

**Comment by TheAssassin** [comment]
Fixed by #55.
