### ISSUE TITLE
missing cmake check for libfuse

### ISSUE THREAD

**Issue by astippich** [AppImage/libappimage#54]
When trying to compile libappimage, it dies during building of squashfuse, unless libfuse development files are installed, but a cmake check for that is missing

**Comment by TheAssassin** [comment]
squashfuse is an optional dependency, which can also be provided by the system (opting out from our custom build). We re-use the existing automake-based tooling to build squashfuse. Unfortunately, CMake runs those only _during the build_, i.e., not during the CMake phase but when running `make` already.

We can surely add a few more tests, but we should only check when not using system libraries. It's the system's duty to take care of dependency management when using those files.

**Comment by azubieta** [comment]
As @TheAssassin said `fuse` is required only if `squashfuse` is built from sources.
We can add a check for such a case.

**Comment by azubieta** [comment]
fixed by #91
