### ISSUE TITLE
Consider using libcrypt

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#56]
https://www.freebsd.org/cgi/man.cgi?crypt(3)

**Comment by probonopd** [comment]
Why should we change a running system?

**Comment by TheAssassin** [comment]
I don't see the advantage. We already ship our own MD5 digest algorithm to not have to depend on "larger" libs. Apart from that, the library doesn't offer anything else of interest.

**Comment by probonopd** [comment]
Please don't introduce additional dependencies unless there is not a totally pressing need. We already have too many for my taste.

**Comment by TheAssassin** [comment]
> We already have too many for my taste.

Such as?

I would be interested in getting rid of our own MD5 implementation, generally spoken. libcrypt isn't heavyweight either, probably has compatible license and can most likely be linked statically.
However, I would want to hear why @azubieta suggests this. The issue doesn't contain any information on this...

**Comment by probonopd** [comment]
What is wrong about our current MD5 implementation? It works, we have no issues with it, so why touch it.

**Comment by TheAssassin** [comment]
It's random code from the Internet that never will be updated. It hasn't been reviewed in depth by me either. Also, we need additional hashing algorithms anyway for other purposes. And I don't necessarily want to maintain such dependencies myself, we don't need to like, ship MD5 another time to a system which already has a few dozens.

**Comment by probonopd** [comment]
Uh, ok, then it must be an old leftover. Has been solved a long time ago. Sorry for the confusion, closing.
