### ISSUE TITLE
Clean up desktop integration files in case of errors

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#60]
There are cases in which the desktop integration process can fail. The current implementation may leave trash files in the user home in such cases. We should clean up them.

**Comment by probonopd** [comment]
We should prepare all the files that are about to be copied to `$HOME` in a temporary location, and then copy them in all at once; for performance reasons. If we do this, we could clean up the failed temporary files _before_ they get copied into `$HOME`.

**Comment by TheAssassin** [comment]
We could introduce some proper "filesystem transactions", i.e., a new class whose objects describe a series of filesystem actions (create directory, copy/move file etc.), remembering already executed operations to allow for rolling them back if a subsequent operation fails (conceptually similar to SQL transactions), etc.
Even special cases like when e.g., overwriting a file needs to be "undone", could be handled in ther as well (with some file pointer magic). We can use this class everywhere we need transactional behavior.
