### ISSUE TITLE
Desktop Entries parser to use at libappimage

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#61]
Desktop Entries parsing and edition is a required functionality in libappimage. The old implementation uses `glib`, new implementation uses xdg-utils. But there are other alternatives which should be reviewed. 
Our candidates so far are:
- glib-2.0
- [linuxdeploy-desktopfile](https://github.com/linuxdeploy/linuxdeploy-desktopfile) 
- [xdg-utils](https://github.com/azubieta/xdg-utils)

**Comment by probonopd** [comment]
If we have the required functionality in linuxdeploy-desktopfile, could we move it over from there to here? Then we would not have yet another dependency.

**Comment by TheAssassin** [comment]
I also thought it might be beneficial to merge both libraries. linuxdeploy-desktopfile has much better tests (a lot of validation of entries to improve conformance with the spec), @azubieta's version has a more elegant parser implementation (although I don't really see the huge benefit of using an AST; linuxdeploy-desktopfile's fast line-wise string processing works fine, too, so we might compare them by LOC or runtime efficiency or something).

Generally not a top priority right now. Will get back to this next week.

**Comment by TheAssassin** [comment]
Going to settle on xdg-utils, migrating as many tests as possible from ld-desktopfile.
