### ISSUE TITLE
Provide function aliaces for the C interface without the verbose argument

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#62]
A new and good logging system should be created after #51 Therefore the "verbose" parameter present in many of the C public interface will no longer be functional. In order to ease the transition to the newly written code, we should create aliases for such functions without the mentioned parameter.

**Comment by TheAssassin** [comment]
It's rather the other way round. The aliases should contain the parameter and just discard it, while the real versions don't have the parameter at all any more.

**Comment by azubieta** [comment]
This will not be possible without major hacks. C doesn't support function overloading. 
See https://stackoverflow.com/questions/2351792/does-c-support-overloading

**Comment by TheAssassin** [comment]
Hm... probably too much used to C++ there. Okay then, closing.
