### ISSUE TITLE
Support interpretation of boolean values at xdg-utils-cpp

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#68]
This code should not have to be in here, your library shall specification details like "interpretation of boolean values". ld-desktopfile can do it (it's conformance tested even).

_Originally posted by @TheAssassin in https://github.com/AppImage/libappimage/timeline_

**Comment by azubieta** [comment]
Support added. Now it must be used at `libappimage`.

**Comment by TheAssassin** [comment]
Wrong project tracker.
