### ISSUE TITLE
Allow return value in AppImage traversal

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/libappimage#7]
At the moment, we have type-specific functions called `appimage_handler::traverse` (if it were C++), which call a callback on every path that matches a given pattern.

The callbacks usually perform name comparisons, for instance:

```c
if (strcmp(params->file_path, filename) == 0)
    // do something meaningful
```

As you can see, in this common case, the callback is only supposed to be run once when the right file has been found, as the comparison checks for equal strings. However, even if the file is found, the loop will continue to call the callback on all the files left in the AppImage.

This is highly inefficient, but luckily, we're not the first ones to solve this problem. There is an elegant way to allow for some "feedback" from the callback to the caller: we simply change the callbacks' return values from `void` to `bool`. Whenever the callback returns `true`, the loop in `traverse` can be aborted. 

Depending on the location of the given path, this will greatly speed up use cases such as `appimage_extract_file_following_symlinks`. Also, our `dummy` functions which we use for testing can become no-ops (`O(1)` instead of `O(n)`).

CC @azubieta @probonopd if you have any points why this is a bad idea, please let me know.

**Comment by alshhrymhmd008** [comment]
O3

**Comment by alshhrymhmd008** [comment]
Osypptl3

**Comment by azubieta** [comment]
I guess that there is no point on improving the libappimage 0.1 code anymore. Will close the issue. Please reopen if required.

**Comment by TheAssassin** [comment]
Only critical bugs or other maintenance.
