### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/libappimage#95]
Until the end of March, I'd like to release libappimage 1.0.0. Being the first stable release we ever provide, this marks a milestone in our development history. This library has been largely rewritten, and now the codebase is ready for more public usage.

**Comment by probonopd** [comment]
I think it needs to be documented before it should be released, and it should be made sure that its consumers (e.g., `appimaged` are updated to work properly with it) first.

**Comment by TheAssassin** [comment]
Release has been published weeks ago. Closing.
