### ISSUE TITLE
Make version and enabled feature set available in binary interface

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#97]
At build time the users can choose if the "desktop integration" and "thumbnails generation" features will be compiled or not. We should provide a reliable way of notifying users if such features were enable at compile time.

Providing a header config file seems the be a common and effective way of doing this.

We should have one of those :).

This could be a good chance to also include the library version.

**Comment by azubieta** [comment]
addressed at #124

**Comment by TheAssassin** [comment]
#124 does not implement anything ABI wise, does it?

**Comment by TheAssassin** [comment]
@azubieta ^

**Comment by azubieta** [comment]
I was (foolishly) hopping that some kind of record were created in the binary. But that will not going to happen. So far such information it's only in the header (API) so no it's not in the ABI. We would need to add a `getVersion` function or declare a global constant with such information to make it available on the ABI

**Comment by TheAssassin** [comment]
I think that'll be overkill then. That kind of stuff is only interesting when you're using `dlopen`, which is not a scenario of use for us right now. I think it's good enough as is, at least for now.

**Comment by azubieta** [comment]
Me too. I will close this issue for the moment. Fell free to reopen if required.
