### ISSUE TITLE
ERROR: appimage_register_in_system : Unable to load libgobject-2.0.so

### ISSUE THREAD

**Issue by azubieta** [AppImage/libappimage#98]
While using `libappimage` in CentOS the `libgobject` binaries have a different name, therefore it will not be loaded.

The lookup method for dynamically loaded libraries must be improved.

**Comment by TheAssassin** [comment]
Seems like we just need a list of filenames and try them until one works for loading?

**Comment by azubieta** [comment]
Fixed by #100
